# SPDX-FileCopyrightText: Copyright (c) 2013-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.19.0
assets:
  npmrc: yegor256/home#assets/npmrc
install: |-
  npm install --no-color
release:
  pre: false
  script: |-
    node --version
    npm -version
    npm test --no-color
    sed -i "s/0.0.0/${tag}/g" package.json
    chmod 600 ../npmrc
    npm publish --no-color --userconfig=../npmrc
merge:
  script: |-
    npm test --no-color
